---
title: "kurvers_2018_reanalysis"
author: "MR"
date: "2026-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
```

```{r load in data}

# Load in data
df<- read.csv("kurvers_et_al_2018_data.csv")


# get sample sizes by treatment and sex
df_counts <- df %>%
  distinct(fish.identity, sex, treatment) %>%   # keep one row per fish
  count(sex, treatment)


df|> distinct(fish.identity) |> count()

df_counts

```

```{r}
library(dplyr)
library(tidyr)

# variables of interest
vars <- c("emergence.time", "activity", "edge.time.perc")


# average variables across trials
df_fish <- df %>%
  group_by(fish.identity, sex, treatment) %>%
  summarise(
    emergence.time = mean(emergence.time, na.rm = TRUE),
    activity = mean(activity, na.rm = TRUE),
    edge.time.perc = mean(edge.time.perc, na.rm = TRUE),
    .groups = "drop"
  )


# 2. pivot longer for easier processing
df_long <- df_fish %>%
  pivot_longer(
    cols = all_of(vars),
    names_to = "variable",
    values_to = "value"
  )


# 3. compute group mean, sd, and n
df_sum <- df_long %>%
  group_by(sex, variable, treatment) %>%
  summarise(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )


# 4. split control vs treatments
control_df <- df_sum %>%
  filter(treatment == "Control") %>%
  rename(
    mean_control = mean,
    sd_control = sd,
    n_control = n
  ) %>%
  select(sex, variable, mean_control, sd_control, n_control)

treat_df <- df_sum %>%
  filter(treatment != "Control") %>%
  rename(
    mean_treatment = mean,
    sd_treatment = sd,
    n_treatment = n
  )

# 5. compute effect sizes (LRR)
es_df <- treat_df %>%
  left_join(control_df, by = c("sex", "variable")) %>%
  mutate(
    yi = log(mean_treatment / mean_control),
    vi = (sd_treatment^2 / (n_treatment * mean_treatment^2)) +
         (sd_control^2 / (n_control * mean_control^2)),
    comparison = paste(treatment, "vs Control")
  )


write_csv(es_df, "es_df.csv")
```

